import builtins from 'builtin-modules';
import * as path from 'path';
import { defineConfig } from 'vite';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY VITE
if you want to view the source, please visit the github repository of this plugin
*/
`;

export default defineConfig({
  build: {
    lib: {
      entry: path.resolve(__dirname, 'main.ts'),
      formats: ['cjs'],
    },
    rollupOptions: {
      output: {
        entryFileNames: 'main.js',
        assetFileNames: 'styles.css',
        banner,
      },
      external: [
        'obsidian',
        'electron',
        '@codemirror/autocomplete',
        '@codemirror/collab',
        '@codemirror/commands',
        '@codemirror/language',
        '@codemirror/lint',
        '@codemirror/search',
        '@codemirror/state',
        '@codemirror/view',
        '@lezer/common',
        '@lezer/highlight',
        '@lezer/lr',
        ...builtins,
      ],
    },
    outDir: '.',
    emptyOutDir: false,
    sourcemap: process.env.NODE_ENV === 'production' ? false : 'inline',
    minify: process.env.NODE_ENV === 'production',
  },
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
    },
  },
});
