import builtins from 'builtin-modules';
import * as fs from 'fs';
import * as path from 'path';
import { defineConfig, Plugin } from 'vite';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY VITE
if you want to view the source, please visit the github repository of this plugin
*/
`;

// Custom plugin to copy build artifacts to TestVault
function copyToTestVault(): Plugin {
  return {
    name: 'copy-to-test-vault',
    closeBundle: async () => {
      const testVaultPluginDir = path.resolve(__dirname, 'TestVault/.obsidian/plugins/obsidian-encrypted-folders');

      // Ensure directory exists
      if (!fs.existsSync(testVaultPluginDir)) {
        fs.mkdirSync(testVaultPluginDir, { recursive: true });
      }

      // Files to copy
      const filesToCopy = [
        { src: 'dist/main.js', dest: 'main.js' },
        { src: 'manifest.json', dest: 'manifest.json' },
        { src: 'styles.css', dest: 'styles.css' },
      ];

      for (const file of filesToCopy) {
        const srcPath = path.resolve(__dirname, file.src);
        const destPath = path.resolve(testVaultPluginDir, file.dest);

        if (fs.existsSync(srcPath)) {
          fs.copyFileSync(srcPath, destPath);
          console.log(`✓ Copied ${file.src} to TestVault`);
        }
      }
    },
  };
}

export default defineConfig({
  plugins: [copyToTestVault()],
  build: {
    lib: {
      entry: path.resolve(__dirname, 'main.ts'),
      formats: ['cjs'],
    },
    rollupOptions: {
      output: {
        entryFileNames: 'main.js',
        assetFileNames: 'styles.css',
        banner,
      },
      external: [
        'obsidian',
        'electron',
        '@codemirror/autocomplete',
        '@codemirror/collab',
        '@codemirror/commands',
        '@codemirror/language',
        '@codemirror/lint',
        '@codemirror/search',
        '@codemirror/state',
        '@codemirror/view',
        '@lezer/common',
        '@lezer/highlight',
        '@lezer/lr',
        ...builtins,
      ],
    },
    outDir: 'dist',
    emptyOutDir: true,
    sourcemap: process.env.NODE_ENV === 'production' ? false : 'inline',
    minify: process.env.NODE_ENV === 'production',
  },
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
    },
  },
});
